### ISSUE TITLE
Refactoring of UI code

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#111]

**Comment by tomas-knap** [comment]
@brodecva Please specify which kind of refactoring is needed. I though it is done by Istvan? Do you mean here the use of directives?  Please also update the milestone

**Comment by istvan-satmari** [comment]
After a discussion with @KataBoku we collectively decided it is best left to her. First, I don't understand the whole code anyway and she already has a brief idea what the result should look like.

Briefly, what we expect from the refactoring:
- modules / components should be split into files
- (components are e.g. table for selection C&D, subject column,  modals - deduplication needed, etc.)
- !! overall, the most important thing to do is to separate code into 'sections' (be it several files, or 'regions', ...) and describe it using comments so that it is easy to use a certain module/component. (e.g. a scenario: a component of mine, graphvis, uses 'locks', which I consider a separate component. It should be easy by looking at comments to understand the usage of the 'locks'.)
- (Anything else is a waste of time.)

**Comment by brodecva** [comment]
@tomas-knap We have a Skype planned with @KataBoku  and @istvan-satmari on Saturday 2016-12-02 morning, that should finally close this issue. @KataBoku will present the results of the re-factorization.

**Comment by istvan-satmari** [comment]
As for the 3/12/2016, TODO for @KataBoku :
- remove unused comments
- add comments describing usage of cdlock.js (cdlock directive)
- rename cdtablerows => cdtablerow

**Comment by istvan-satmari** [comment]
Merged. Hopefully everything works.
