### ISSUE TITLE
Extend, rename and group the export buttons

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#120]
JSON to Table annotations, CSV to Extended table (and group these two, as they are two parts of a single export format).
Currently both the JSON-LD a Turtle formats for RDF data are supported, please split the RDF button to two and assign them those formats names (and link them to request with appropriate Accept headers: applications/ld+json,  text/turtle).

**Comment by istvan-satmari** [comment]
"link them to request with appropriate Accept headers" => not possible. See: http://stackoverflow.com/questions/4325968/window-open-with-headers

"...please split the RDF button to two..." => please, add the necessary info to grips/REST API, since I don't remember the exact requests to pull this off.

**Comment by brodecva** [comment]
> "...please split the RDF button to two..." => please, add the necessary info to grips/REST API, since I don't remember the exact requests to pull this off.

Done.

**Comment by istvan-satmari** [comment]
Seems to be working well, thank you.
