### ISSUE TITLE
When there is a problem creating resource in the knowledge it must not be added to the result table (and feedback)

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#155]
It must not happen that in case there is error when proposing concept  (concept cannot be added to the knowledge base), it is still added to the Table in UI!!

**Comment by brodecva** [comment]
This is interesting. The API specifically declares that the proposed entity is successfully stored in the KB only when the replay is OK and the newly created is returned in the payload. So the client should not technically be able to add an entity to the result or feedback, because it has none available.

**Comment by tomas-knap** [comment]
Probably Kata immediately adds the proposed concept without waiting for result of the API call

**Comment by brodecva** [comment]
Fixed and about to be pushed by @KataBoku .

**Comment by tomas-knap** [comment]
Please point to the commit where it was fixed

**Comment by brodecva** [comment]
This is fixed in https://github.com/odalic/odalic-ui/commit/c836f29858eadc9c6747fa629cd68b29368fe2e5 , albeit there is not time out for this operation, so if the connection is down, the client does nothing. I have created an issue #204 dealing with this matter.
