### ISSUE TITLE
Configuration import/export buttons and dialogs

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#168]
_From @brodecva on November 30, 2016 0:41_

Stories at https://grips.semantic-web.at/x/I4F2B and https://grips.semantic-web.at/x/JYF2B.

_Copied from original issue: odalic/sti#229_

**Comment by brodecva** [comment]
Waits for https://github.com/odalic/sti/issues/163 .

**Comment by tomas-knap** [comment]
Please till 7.2. if possible

**Comment by istvan-satmari** [comment]
I marked it as closed because I want to move on, but, there are some issues.
Exporting works (see taskconfigs screen).
Import does not seem to work correctly, though, but I am unable to detect the cause - the server responds with an empty message and 406 status. I would assume it is my fault somewhere in the code, but the request I am sending to the server seems to conform to the specification.
Please, @brodecva , could you find out why the server behaves unexpectedly? Thanks!

**Comment by istvan-satmari** [comment]
Sorry, my bad - incorrect accept type of the request. 
It should work now.
