### ISSUE TITLE
There must be tooltips showing full names of the nodes in the relations graph

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#173]
Names of the column may be shortened - there must be a possibility to get full label - e.g. in the tooltip? Relates with https://github.com/odalic/odalic-ui/issues/172

**Comment by tomas-knap** [comment]
If easy, it would be really good to add. The graph with relations now looks better: 

![screen shot 2017-01-12 at 12 41 17](https://cloud.githubusercontent.com/assets/3014917/21888436/91f12414-d8c4-11e6-921d-367f0c6571ab.png)

But there is an issue that two nodes have the exact same label, so I cannot differentiate them. Tooltips would be enough.

**Comment by istvan-satmari** [comment]
No tooltips, but on mouse hover the full name is displayed. Was easier to implement this way (otherwise there is a need for a floating tooltip and detecting current absolute x/y pos of a node, which is a little bit complicated)

**Comment by tomas-knap** [comment]
Ok, thanks!

**Comment by tomas-knap** [comment]
This does not work for me neither in Chrome or in Safari. In which browser did you test that?

**Comment by brodecva** [comment]
@istvan-satmari @tomas-knap Works in Firefox.

**Comment by istvan-satmari** [comment]
todo: chrome/edge test + correction

**Comment by istvan-satmari** [comment]
![edge](https://cloud.githubusercontent.com/assets/17832462/22107369/ad1d51fc-de4d-11e6-85f5-88b9e4fcf95a.png)
![chrome](https://cloud.githubusercontent.com/assets/17832462/22107370/ad57c13e-de4d-11e6-8da5-ee668edce859.png)
Both Edge and Chrome work well. (Firefox works as well, obviously.) 
It seems to me a certain action must have caused an exception (the graph on your screenshot does not even show any relations, which it probably should) and the graphvis component stopped working properly. That is just a guess, though.
Anyway, this issue is closed.

**Comment by tomas-knap** [comment]
Works
