### ISSUE TITLE
Second and third row are both highlighted in the manner of alternating odd and even rows

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#183]

**Comment by tomas-knap** [comment]
See also report from testing this dataset: https://grips.semantic-web.at/display/ADEQ/Results+of+elections+in+Voralrlberg+2009, 

In this case instead of 20lines which should be depicted, only 10 of them were depicted - so:
1) all rows should be depicted
2) this will also correct the highlighting

So the problem is that certain lines are simply not drawn?

**Comment by tomas-knap** [comment]
In certain cases no row is depicted at all, see: https://grips.semantic-web.at/display/ADEQ/Table+of+States

So this is quite urgent

**Comment by istvan-satmari** [comment]
Unfortunately I get an error when processing the task: CSV file is not consistent: data row with index 0 has different size than header row.

**Comment by brodecva** [comment]
@josef-janousek explained the correct procedure to use the provided test files to replicate the bug to @istvan-satmari . @istvan-satmari will look into it.

**Comment by istvan-satmari** [comment]
Seems I won't be able to deal with this from home - possibly due to internet connection. I get "Connection timed out: connect..." exception.
It also takes more than 40 minutes to 'complete' (though I haven't fully reached that state yet). 
Could you, please, provide a result I could use as a "fake" (just for testing purposes)?

**Comment by brodecva** [comment]
@istvan-satmari Please verify if this is a still problem. If yes, please fix that.

**Comment by tomas-knap** [comment]
This should not happen anymore - I think it was cause by skipping certain rows due to bug with indexing cells
