### ISSUE TITLE
When opening a dialog, the focus and prompt should be correctly set

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#226]
E.g. in the case of Create task, the focus should be on the name field, the prompt should be present there, so I can immediately start to write the name of the task, instead of clicking there first.

**Comment by istvan-satmari** [comment]
nice-to-have feature; low prio

**Comment by istvan-satmari** [comment]
I implemented the feature for "create new task" and "import task".
It seems that UI-bootstrap's modal, which @KataBoku uses for task result, already comes with that feature, so e.g. propose modal has focus correctly set.
Otherwise I am not sure what other dialogs should have that feature as well (there is not that many of them anyway), so I'm closing the issue.
