### ISSUE TITLE
Create a demo using the most suitable approach to browse the KB

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#23]
Client-side solution might be preferred.

See https://grips.semantic-web.at/x/-wBsB for details. The https://grips.semantic-web.at/x/-wBsB is based on this.

**Comment by tomas-knap** [comment]
Please write the finding here: https://grips.semantic-web.at/display/ADEQ/Integrating+LodView+and+LodLive+with+Odalic

**Comment by tomas-knap** [comment]
I already added couple of ways how we can realize that. @istvan-satmari  Please review. 
https://grips.semantic-web.at/display/ADEQ/Integrating+LodView+and+LodLive+with+Odalic

**Comment by istvan-satmari** [comment]
Thank you for the proposed solutions.
All of the approaches seem acceptable, but the one I like most is "cross-page communication" (using JavaScript message passing).
That is because it gives us what we actually need - just a response from another window. It is also the most consistent approach (use something that was actually intended for such a job), takes less time to implement (no complex state saving and restoring), shouldn't have any side effects (getting a response from another webpage isn't the same as saving a state) and overall feels like the 'correct solution'. I may be wrong, though.
A demo will be implemented once the relations component is done.

**Comment by brodecva** [comment]
> A demo will be implemented once the relations component is done.

I just felt that it would be better to focus @istvan-satmari solely to the problem with relations first. It is a demanding task on its own and I feel it is better to no distract him with another technical problem until we he will have managed this one. I also feel that @KataBoku might be able to make the lod-view component work on its own (or with some minor assistance from @istvan-satmari ) if we got to the point that @istvan-satmari won't be ready with the relations display.

If you don't agree @tomas-knap , please let us know, and we will revert to the previous plan of simultaneous development of both the relations and KB browsing component.

As @istvan-satmari will be out for the next week, we may have still time to re-evaluate this approach.

**Comment by brodecva** [comment]
Let us move the conversation to #26 . This issues, which dealt with the demonstration of KB browsing, is effectively closed.
