### ISSUE TITLE
When existing task configuration loaded, the chosen KBs and chosen primary KB are not selected

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#305]

**Comment by istvan-satmari** [comment]
They are, this is implemented. The load is asynchronous (no other way, otherwise browser would freeze), so it may take a few seconds. If the load fails, it should display an alert with an appropriate message.
...so, what exactly is not working for you? Because it works perfectly fine on my browser(s) (not just firefox).

**Comment by istvan-satmari** [comment]
Hopefully it works now...
