### ISSUE TITLE
Editing task configuration - knowledge bases forgotten

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#310]
As revealed on Friday, knowledge bases are not always properly selected when editing task configuration. So sometimes it happens that after opening the conf, you have to re-select knowledge bases again

**Comment by istvan-satmari** [comment]
I am not sure whether the bug persists, but I doubt it - the error was caused by a race condition (2 calls for reentering digest cycle), which has been removed. If the selected bases are not loaded, it may be you have not waited enough (< 5 secs should be enough, however).

BTW, correction of the bug tested in Firefox, Chrome.

**Comment by brodecva** [comment]
@istvan-satmari @tomas-knap It works for me now. Closing.
