### ISSUE TITLE
Extend the UI with screens defining the used endpoints

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#374]
In Czech:
Přidat endpoint musí jít uživatelsky a pomocí API

**Comment by tomas-knap** [comment]
Idea:
There is an extra menu item Knowledge Bases, where you can see list of KB (name, endpoint, state). State is either OK or Error (in case of error some info that e.g. during initialization of the KB during startup certain issue occur and such KB is not available in the tasks).

There is a possibility to add KB. In that case, I can define name, sparql endpoint and also some other configurations (for predicates/classes there should be combo-boxes with predefined values). 

Note: When creating new KB it may be a bit boring to fill in such stuff, so there should be a way how to create KB from an existing

There is a possibility to edit KB. But if someone edits KB, what would that mean for the running/finished tasks? I would suggest to make the name of the KB uneditable. 

Note: Write down who can do what - change KB, delete KB etc. 

Next steps - write down requirements/prepare mockups for that - in gdrive, so that Jakub can edit

**Comment by istvan-satmari** [comment]
Not done:
- state
- create a KB from existing
- disable editing when a task is running.
Most of the other requirements were satisfied, however.
Please, let me know what to do with the unsatisfied requirements - state is a server implementation, "disable editing when a task is running" - again I need that information (about a KB being in use) from the server
"Create a KB from existing" can be done on its own (provided I'll have enough time to do so).

**Comment by brodecva** [comment]
> Not done:
>  state

I am inclined to drop this one and just check the state during definition and then during a task run. The first reason is that even if the state is OK, this does not guarantee anything; the error flag is useful, but the user will find out anyway when the first defined task using this base fails. The second one is that it introduces a state to the now immutable KB definitions, so it requires a separate service keeping the states, which means some work that might be invested elsewhere.

>    disable editing when a task is running.

Well once a task is started the KB definition is used to define the actual one-time proxy. Subsequent changes have no effect on the current run. Is it enough?

**Comment by istvan-satmari** [comment]
Ok, I am assigning this to @tomas-knap ; if everything is OK, please, close the issue.

**Comment by brodecva** [comment]
Implemeted as of https://github.com/odalic/sti/commit/d44026159d0136e004b6889128fb1ec2dafceb9f .
