### ISSUE TITLE
Jumps when using tooltips in Chrome

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#454]
In Czech:
> e. V prohlížeči Chrome při zobrazování tooltipů stránka různě skáče.

**Comment by brodecva** [comment]
Cannot confirm, do you have any idea, @istvan-satmari , @KataBoku or @josef-janousek ?

**Comment by istvan-satmari** [comment]
Confirmed
page: /index.html#/createnewtask
resolution: 1920x1080, 100% zoom (i.e. default appearance)
tooltip: "statistical data" label

This is expected since the corresponding tooltip is too long and takes more of the page (it cannot fit), thus vertical scrollbar appears (but only for the time of existence of the tooltip).

While I successfully pushed the footer of the page further below (so the vertical scrollbar is ALWAYS present), I still think the tooltip is too long.
Please, consider reducing its length. (If not, simply put this issue among closed ones, since visually it is OK, I think.)

**Comment by brodecva** [comment]
> Confirmed
page: /index.html#/createnewtask
resolution: 1920x1080, 100% zoom (i.e. default appearance)
tooltip: "statistical data" label

> This is expected since the corresponding tooltip is too long and takes more of the page (it cannot fit), thus vertical scrollbar appears (but only for the time of existence of the tooltip).

> While I successfully pushed the footer of the page further below (so the vertical scrollbar is ALWAYS present), I still think the tooltip is too long.
Please, consider reducing its length. (If not, simply put this issue among closed ones, since visually it is OK, I think.)

Fair enough, I'll look into it.

**Comment by brodecva** [comment]
I have shortened the label in https://github.com/odalic/odalic-ui/commit/2b6dbce3f379ff190937e9a110ebcfe9830f7635 . i would revert the moved footer change, it creates unnecessary empty space
