### ISSUE TITLE
Main content area (task result, creation) should use the whole space available

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#59]
Please adjust the main content area (e.g. task result), so that it uses whole width and height of the screen. See below, it looks ugly and causes not all value are visible (would be even worse for csv files with more column). 

![screen shot 2016-08-30 at 12 02 55](https://cloud.githubusercontent.com/assets/3014917/18085042/bd29db88-6ea9-11e6-9ccc-d1759e8ea0b2.png)

**Comment by istvan-satmari** [comment]
I dare to object it doesn't look ugly and it was an intention (originally I created the template for another website), but I guess everybody has his/her own preferences.

Nevertheless I corrected it. The problem is the footer area, which is not always positioned at the bottom (specifically, when the page occupies less than 100% of the screen height). It seems that either the bootstrap framework has no implicit support for it, or its solution simply doesn't work on our template. Solving this would require non-trivial rewriting of certain css/less scripts + many html changes. So I propose we leave it as it is now, or remove the footer completely.

**Comment by brodecva** [comment]
>I dare to object it doesn't look ugly and it was an intention (originally I created the template for another website), but I guess everybody has his/her own preferences.

I am sure Tomáš meant no harm. :-)

> The problem is the footer area, which is not always positioned at the bottom (specifically, when the page occupies less than 100% of the screen height). It seems that either the bootstrap framework has no implicit support for it, or its solution simply doesn't work on our template. Solving this would require non-trivial rewriting of certain css/less scripts + many html changes. So I propose we leave it as it is now, or remove the footer completely.

I see. It does not bother me that much. I will assign the issue to @tomas-knap and let him decide if it is acceptable, or it can be done later, or kept without change as it is.

**Comment by tomas-knap** [comment]
Testing that in Safari, the footer seems to work in a way that it appears directly below the main content part (if it doe not occupy whole screen, it is in the middle of the screen). This is OK. No need to invest further time on that. 

<img width="1437" alt="screen shot 2016-09-20 at 18 40 53" src="https://cloud.githubusercontent.com/assets/3014917/18680004/28fad6a0-7f62-11e6-97de-5f1fda89a706.png">

**Comment by tomas-knap** [comment]
So it is solved.
