### ISSUE TITLE
No difference between "fixed node" and status "node dragging"

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#62]
When I fix position of certain node, it looks as follows (right node was fixed):
![screen shot 2016-08-30 at 12 39 09](https://cloud.githubusercontent.com/assets/3014917/18086179/e0d9e046-6eae-11e6-9f19-c92c059c3def.png)
But when I then swith to "link creation", there is no difference between the colors of the nodes!:
![screen shot 2016-08-30 at 12 39 14](https://cloud.githubusercontent.com/assets/3014917/18086178/e0d8b6ee-6eae-11e6-88cd-3d7188e2ebf1.png)

It should be possible to differentiate between the "fixed node" and status "node dragging".

**Comment by brodecva** [comment]
I am not sure if I understand @tomas-knap 's description of what he really wants, so I state it in my own words:
1. In the current form, the left button bears the name of mode that the user will enter when he or she hits the button. This is confusing, because the user has hard time to immediately know in which mode the graph currently resides and also the button Reset layout does not work this way (it has the semantics of a common button, because it does some stateless action). Therefore I think that the Node dragging/Link creation button should not be a single button, but rather something more akin to a true switch. This could be implemented by adding another dedicated "button" to the left and leaving the last clicked of the pair Node dragging - Link creation with colours inverted to indicate the current mode.

2. Concerning the background of nodes in both modes, I would suggest to use a different colour in the Link creation mode from the two used to indicate fixed and floating node in the Node dragging mode. It will not only help the user to distinguish between the two modes, but also not confuse him into trying to unfix a node (by not sharing the same, red color) when in the Link creation mode.

Please, @istvan-satmari , fix that. Especially the 2. should not be that hard to do.

**Comment by istvan-satmari** [comment]
Especially the #2 is relatively hard to do, because of the 'state machine'  the graph uses: from the graph's point when user wants to 'create links', it puts each node into 'fixed' state (if not already). This to me seems logical. I did not expect somebody would want to differentiate between those two.

I may look into this, but no guarantees so soon.

**Comment by tomas-knap** [comment]
I would suggest to do 1) (in the Vasek's feedback) later in the next iteration. @brodecva Please separate that to a new issue. 

What I meant in this issue is really just having two different colours for two different actions - so as Vasek summarizes under point 2). But now I also understand explanation of Istvan - that basically by switching to "edge creation", nodes are fixed for that time (and release again when switch to node dragging). 

@istvan-satmari Can you please just change the red color to something which is not that expressive? Then I would suggest to close this issue.

**Comment by istvan-satmari** [comment]
Nvm, I fixed all. Check the latest commit on github if it suits your needs.

**Comment by brodecva** [comment]
> Nvm, I fixed all. Check the latest commit on github to see if it suits your needs.

@istvan-satmari As always, you outdid yourself. Thanks!

**Comment by istvan-satmari** [comment]
"As always, you outdid yourself." - that's encouraging, thanks! :D ...You are welcome.
